version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bank_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bank
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
